kind: pipeline
name: I-Ching

platform:
  arch: amd64

steps:
- name: build
  image: tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7
  commands:
  - python3 -m venv appvenv
  - . appvenv/bin/activate
  - pip install -r requirements.txt
  - export FLASK_APP=iching
  - export FLASK_ENV=development

- name: test
  image: tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7
  commands:
  - python3 -m unittest discover -v